// Structure of a portfolio Thumbnails
export type PortfolioItem = {
    id: string
    key: string
    title: string
    category: string
    type: string
    tags: string[]
    img: string
    bgClass: string
    order: number
    protected: 'yes' | 'no'
    showProject: 'yes' | 'no'
}

// Data for Thumbnails
export const allPortfolio: PortfolioItem[] = [
    {
        id: '8',
        key: 'MUIK',
        title: 'Motion UI Kit',
        category: 'Personal Product',
        type: 'Design + Code',
        tags: ['React', 'Framer Motion', 'Design Systems'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-MUIK.webp',
        bgClass: 'card-background-MUIK',
        order: 1,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '7',
        key: 'startoken',
        title: 'Startoken — Design Token Pipeline (Figma → Code)',
        category: 'Personal Product',
        type: 'Design Systems',
        tags: ['Design Tokens', 'Figma', 'React', 'TypeScript'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-startoken2.webp',
        bgClass: 'card-background-startoken',
        order: 2,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '5',
        key: 'Aleph',
        title: 'Aleph Design System',
        category: 'Professional',
        type: 'Design Systems',
        tags: ['Components', 'Foundations', 'Visual Design'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-aleph2.webp',
        bgClass: 'card-background-aleph',
        order: 3,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '6',
        key: 'hub',
        title: 'Hub Design System',
        category: 'Professional',
        type: 'Design Systems',
        tags: ['Components', 'UI Design', 'Systems'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-hub-design-system.webp',
        bgClass: 'card-background-hub',
        order: 4,
        protected: 'yes',
        showProject: 'yes',
    },
    {
        id: '2',
        key: 'av',
        title: 'AV Expert App',
        category: 'Professional',
        type: 'Product UI',
        tags: ['UI Design', 'Interaction', 'Mobile'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-av-expert2.webp',
        bgClass: 'card-background-av',
        order: 5,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '1',
        key: 'solve',
        title: 'Solve For Tomorrow',
        category: 'Professional',
        type: 'Product Design',
        tags: ['UX/UI', 'Visual Design', 'Prototyping'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-solve-for-tomorrow2.webp',
        bgClass: 'card-background-solve',
        order: 6,
        protected: 'no',
        showProject: 'yes',
    },

    {
        id: '3',
        key: 'essilor',
        title: 'Essilor App',
        category: 'Professional',
        type: 'Product UI',
        tags: ['Mobile', 'UI Design', 'Prototyping'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-essilor2.webp',
        bgClass: 'card-background-essilor',
        order: 6,
        protected: 'no',
        showProject: 'yes',
    },

    {
        id: '4',
        key: 'landing',
        title: 'Landing S21',
        category: 'Professional',
        type: 'UI/Visual',
        tags: ['Visual Design', 'UI', 'Prototyping'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-landing-s21-2.webp',
        bgClass: 'card-background-landing',
        order: 7,
        protected: 'no',
        showProject: 'yes',
    },
]

export const uiVisualPortfolio: PortfolioItem[] = [
    {
        id: '2',
        key: 'av',
        title: 'AV Expert App',
        category: 'Professional',
        type: 'Product UI',
        tags: ['UI Design', 'Interaction', 'Mobile'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-av-expert2.webp',
        bgClass: 'card-background-av',
        order: 3,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '1',
        key: 'solve',
        title: 'Solve For Tomorrow',
        category: 'Professional',
        type: 'Product Design',
        tags: ['UX/UI', 'Visual Design', 'Prototyping'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-solve-for-tomorrow2.webp',
        bgClass: 'card-background-solve',
        order: 4,
        protected: 'no',
        showProject: 'yes',
    },

    {
        id: '3',
        key: 'essilor',
        title: 'Essilor App',
        category: 'Professional',
        type: 'Product UI',
        tags: ['Mobile', 'UI Design', 'Prototyping'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-essilor2.webp',
        bgClass: 'card-background-essilor',
        order: 5,
        protected: 'no',
        showProject: 'yes',
    },
]

export const codePortfolio: PortfolioItem[] = [
    {
        id: '8',
        key: 'MUIK',
        title: 'Motion UI Kit',
        category: 'Personal Product',
        type: 'Design + Code',
        tags: ['React', 'Framer Motion', 'Design Systems'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-MUIK.webp',
        bgClass: 'card-background-MUIK',
        order: 1,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '7',
        key: 'startoken',
        title: 'Startoken — Design Token Pipeline (Figma → Code)',
        category: 'Personal Product',
        type: 'Design Systems',
        tags: ['Design Tokens', 'Figma', 'React', 'TypeScript'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-startoken2.webp',
        bgClass: 'card-background-startoken',
        order: 2,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '1',
        key: 'solve',
        title: 'Solve For Tomorrow',
        category: 'Professional',
        type: 'Product Design',
        tags: ['UX/UI', 'Visual Design', 'Prototyping'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-solve-for-tomorrow2.webp',
        bgClass: 'card-background-solve',
        order: 3,
        protected: 'no',
        showProject: 'yes',
    },
]

export const dsPortfolio: PortfolioItem[] = [
    {
        id: '8',
        key: 'MUIK',
        title: 'Motion UI Kit',
        category: 'Personal Product',
        type: 'Design + Code',
        tags: ['React', 'Framer Motion', 'Design Systems'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-MUIK.webp',
        bgClass: 'card-background-MUIK',
        order: 1,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '7',
        key: 'startoken',
        title: 'Startoken — Design Token Pipeline (Figma → Code)',
        category: 'Personal Product',
        type: 'Design Systems',
        tags: ['Design Tokens', 'Figma', 'React', 'TypeScript'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-startoken2.webp',
        bgClass: 'card-background-startoken',
        order: 2,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '5',
        key: 'Aleph',
        title: 'Aleph Design System',
        category: 'Professional',
        type: 'Design Systems',
        tags: ['Components', 'Foundations', 'Visual Design'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-aleph2.webp',
        bgClass: 'card-background-aleph',
        order: 3,
        protected: 'no',
        showProject: 'yes',
    },
    {
        id: '6',
        key: 'hub',
        title: 'Hub Design System',
        category: 'Professional',
        type: 'Design Systems',
        tags: ['Components', 'UI Design', 'Systems'],
        img: 'https://sebastiangonzalez.design/images/thumbnails/thumbnail-hub-design-system.webp',
        bgClass: 'card-background-hub',
        order: 4,
        protected: 'yes',
        showProject: 'yes',
    },
]
